server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-boot
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: spring-boot
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot